import { test, expect } from "@playwright/test";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";

test("Granola selection through Jev classification to reviewed CRM evidence",async({page,request})=>{
  await page.goto("/");
  await page.locator("aside").getByRole("button",{name:"Calls",exact:true}).click();
  const calls=page.locator('[data-view="calls"]');
  await page.screenshot({path:"test-results/calls-empty.png"});
  await calls.getByLabel("API key",{exact:true}).fill("fixture-session-key");
  await calls.getByRole("button",{name:"Check and connect"}).click();
  await expect(calls.getByText(/Jev: connected/)).toBeVisible();
  await calls.getByLabel("Provider",{exact:true}).selectOption("granola");
  await calls.getByLabel("API key",{exact:true}).fill("fixture-granola-key");
  await calls.getByRole("button",{name:"Check and connect"}).click();
  await expect(calls.getByRole("button",{name:"Browse Granola"})).toBeEnabled();
  await calls.getByRole("button",{name:"Browse Granola"}).click();
  await calls.getByLabel("Synthetic pilot call",{exact:true}).check();
  await calls.getByRole("button",{name:"Import 1 calls",exact:true}).click();
  await expect(calls.getByText(/Imported 1 calls in/)).toBeVisible();
  await calls.getByText("Send the selected transcript content to TypeSafe for Jev processing.").click();
  await calls.getByRole("button",{name:"Process 1 calls with Jev"}).click();
  await expect(calls.getByText("fixture-provider (test only)",{exact:false})).toBeVisible();
  await expect(calls.getByText("conditional",{exact:true})).toBeVisible();
  const review=calls.getByRole("region",{name:"Call review"});
  await expect(calls.getByRole("button", {name:"Customer needs · 1",exact:true})).toBeVisible();
  await expect(calls.getByRole("button", {name:"Commitments · 1",exact:true})).toBeVisible();
  await review.getByText("Why this update?", {exact:true}).last().click();
  await expect(review.getByText(/Keep the condition attached/)).toBeVisible();
  await page.screenshot({path:"test-results/calls-questions.png"});
  await review.getByText("Why this update?", {exact:true}).last().click();
  await review.locator('input[type="checkbox"]').first().check();
  await review.getByLabel("Save to account").selectOption({label:"Northstar Robotics"});
  await expect(review.getByRole("heading", {name:"Update Northstar Robotics"})).toBeVisible();
  await review.scrollIntoViewIfNeeded();
  await page.screenshot({path:"test-results/calls-desktop.png"});
  await page.setViewportSize({width:390,height:844});
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await review.scrollIntoViewIfNeeded();
  await page.screenshot({path:"test-results/calls-mobile.png"});
  await page.setViewportSize({width:1440,height:1000});
  await review.getByRole("button",{name:"Save 1 reviewed quote"}).click();
  await expect(calls.getByText("Saved to account",{exact:true})).toBeVisible();
  await expect(review.getByText("Not saved",{exact:true})).toBeVisible();
  await expect(review.locator('input[type="checkbox"]').first()).toBeChecked();
  await review.scrollIntoViewIfNeeded();
  await page.screenshot({path:"test-results/calls-saved.png"});
  await page.getByRole("button",{name:"Toggle theme"}).click();
  await page.screenshot({path:"test-results/calls-dark.png",animations:"disabled"});
  const disk=JSON.parse(fs.readFileSync(path.join(os.tmpdir(),`open-crm-calls-e2e-${Number(process.env.OPEN_CRM_PORT || 5221)+2}`,"workspace.json"),"utf8"));
  const note=disk.notes.find((n:any)=>n.title==="Synthetic pilot call");
  expect(note.sourceRef).toMatch(/^source:/);
  expect(disk.claims.some((c:any)=>c.evidence.includes(note.id))).toBe(true);
  expect(JSON.stringify(disk)).not.toContain("fixture-session-key");
  expect(await page.evaluate(()=>JSON.stringify(localStorage))).not.toContain("fixture-session-key");
  const state=await request.get("/api/calls");
  expect(await state.text()).not.toContain("fixture-session-key");
  const cross=await request.post("/api/calls/process",{headers:{Origin:"https://untrusted.example"},data:{ids:[],consent:true}});
  expect(cross.status()).toBe(403);
  await page.getByRole("button",{name:"Toggle theme"}).click();
  await review.getByRole("button", {name:"Open updated account"}).click();
  const accountView = page.locator('[data-view="accounts"]');
  await expect(accountView).toBeVisible();
  await expect(accountView.getByText("speaker: We need a clearer audit trail.", {exact:true}).first()).toBeVisible();
  await page.screenshot({path:"test-results/calls-account.png"});
  await page.locator("aside").getByRole("button",{name:"Calls",exact:true}).click();
  await calls.locator("summary").filter({hasText:"Import calls"}).click();
  await calls.locator('input[type="file"]').setInputFiles({name:"Synthetic failure.txt",mimeType:"text/plain",buffer:Buffer.from("Speaker: FAILING_FIXTURE synthetic failure case.")});
  await calls.getByLabel("Select Synthetic failure.txt",{exact:true}).check();
  await calls.getByRole("button",{name:"Process 1 calls with Jev"}).click();
  await expect(calls.getByText("The provider rejected this key or its access scope. Check it in Connections.",{exact:true})).toBeVisible();
  await page.screenshot({path:"test-results/calls-error.png"});
  await calls.getByRole("button",{name:"Try 50 sample calls"}).click();
  await expect(calls.getByRole("button",{name:"Process 50 calls with Jev"})).toBeEnabled();
  await calls.getByRole("button",{name:"Process 50 calls with Jev"}).click();
  await expect(calls.getByText("50 / 50 processed · 0 failed",{exact:false})).toBeVisible();
  await calls.getByRole("button", {name:"Commitments · 51",exact:true}).click();
  await expect(calls.getByRole("button", {name:"Commitments · 51",exact:true})).toHaveAttribute("aria-pressed","true");
  await expect(review.locator("blockquote").filter({hasText:"We need"})).toHaveCount(0);
  await page.screenshot({path:"test-results/calls-batch.png"});
  await calls.getByRole("button", {name:"Objections · 0",exact:true}).click();
  await expect(calls.getByText("No calls in this group. Choose another result above.")).toBeVisible();
});
