import type { Account, Deal, Note, Task, Workspace } from "../types.ts";
import { accountStageLabel, dealStageLabel, noteSourceLabel, slugify } from "./model.ts";

/**
 * Markdown views of a workspace: one file per account plus an index. They are
 * what an agent reads and what a person opens in Obsidian or on GitHub. Every
 * record carries its id in backticks so a reader can cite it and a command can
 * address it. Dates are ISO days so the files diff cleanly under git.
 */

export type ViewFile = { path: string; content: string };

export interface ViewLayout {
  /** Folder for account files, with a trailing slash, or "" for a flat vault. */
  accountDir: string;
  indexPath: string;
}

export const vaultLayout: ViewLayout = { accountDir: "", indexPath: "_index.md" };
export const workspaceLayout: ViewLayout = { accountDir: "accounts/", indexPath: "INDEX.md" };

export const GENERATED_NOTICE =
  "<!-- Generated by Open CRM from workspace.json. Do not edit: changes here are overwritten. Use the crm command to change records. -->";

// Quote scalar YAML values so names with `:`, leading `#`, or brackets stay valid.
const yq = (value: string) => JSON.stringify(value);
const day = (iso: string | null) => iso?.slice(0, 10) ?? "unknown";
const tick = (id: string) => `\`${id}\``;

export function accountMarkdown(account: Account, deals: Deal[], tasks: Task[], notes: Note[], notice = false): string {
  const frontmatter = [
    "---",
    `id: ${yq(account.id)}`,
    `title: ${yq(account.name)}`,
    "type: crm-account",
    `stage: ${yq(account.stage)}`,
    `priority: ${yq(account.priority)}`,
    `owner: ${yq(account.owner)}`,
    `arr: ${account.arr}`,
    `health: ${account.health}`,
    `fit: ${account.fit}`,
    `tags: [${["crm", ...account.tags].map((tag) => JSON.stringify(tag)).join(", ")}]`,
    `lastInteraction: ${account.lastTouch ? yq(account.lastTouch) : "null"}`,
    `archived: ${Boolean(account.archivedAt)}`,
    "---",
  ].join("\n");

  const lines: string[] = [frontmatter, ""];
  if (notice) lines.push(GENERATED_NOTICE, "");
  lines.push(`# ${account.name}`, "", `*${account.segment} · ${account.domain} · ${accountStageLabel[account.stage]}*`, "");

  lines.push("## Needs", ...(account.needs.length ? account.needs.map((need) => `- ${need}`) : ["- None recorded"]), "");
  lines.push("## Risks", ...(account.risks.length ? account.risks.map((risk) => `- ${risk}`) : ["- None recorded"]), "");

  if (account.contacts.length) {
    lines.push("## Contacts");
    for (const contact of account.contacts) {
      lines.push(`- **${contact.name}** — ${contact.role} (${contact.influence})${contact.email ? ` · ${contact.email}` : ""} ${tick(contact.id)}`);
    }
    lines.push("");
  }

  if (deals.length) {
    lines.push("## Deals");
    for (const deal of deals) {
      lines.push(
        `- **${deal.name}** — ${dealStageLabel[deal.stage]}, $${deal.value.toLocaleString("en-US")} · ${deal.probability}% · close ${day(deal.closeDate)} ${tick(deal.id)}`,
      );
    }
    lines.push("");
  }

  const openTasks = tasks.filter((task) => task.status === "open" || task.status === "waiting");
  if (openTasks.length) {
    lines.push("## Open tasks");
    for (const task of openTasks) {
      lines.push(`- [ ] ${task.title} (${task.status}, ${task.status === "waiting" ? "review" : "due"} ${day(task.due)}, ${task.priority}, ${task.owner}) ${tick(task.id)}`);
      if (task.reason) lines.push(`  - Why: ${task.reason}`);
      if (task.evidence?.length) lines.push(`  - Evidence: ${task.evidence.map(tick).join(", ")}`);
    }
    lines.push("");
  }

  if (notes.length) {
    lines.push("## Notes");
    for (const note of notes) {
      lines.push(
        `### ${note.title} ${tick(note.id)}`,
        `*${noteSourceLabel[note.source]} · source date ${note.occurredAt ? day(note.occurredAt) : "unknown"} · captured ${day(note.createdAt)} · ${note.interaction ? "verified interaction" : "not verified contact"} · ${note.sentiment}${note.origin ? ` · captured by ${note.origin.name}` : ""}*`,
        `Source reference: ${note.sourceRef || "Not recorded"}`,
        "",
        note.body,
        "",
      );
    }
  } else {
    lines.push("## Notes", "No source notes recorded. Do not invent account context; capture a source first.", "");
  }

  return lines.join("\n");
}

/** Collision-proof slug per account, keyed by the unique account id. */
export function uniqueSlugs(accounts: Account[]): Map<string, string> {
  const used = new Set<string>();
  const slugs = new Map<string, string>();
  for (const account of accounts) {
    const base = slugify(account.name);
    let candidate = base;
    let i = 2;
    while (used.has(candidate)) candidate = `${base}-${i++}`;
    used.add(candidate);
    slugs.set(account.id, candidate);
  }
  return slugs;
}

export function indexMarkdown(workspace: Workspace, slugs: Map<string, string>, layout: ViewLayout, notice = false): string {
  const lines = ["---", `title: ${yq(workspace.name)}`, "type: crm-index", `updated: ${yq(workspace.updatedAt)}`, "---", ""];
  if (notice) lines.push(GENERATED_NOTICE, "");
  lines.push(`# ${workspace.name}`, "", "| Account | Stage | Priority | Owner | Health | Last touch | Id |", "| --- | --- | --- | --- | --- | --- | --- |");
  for (const account of workspace.accounts) {
    const link = `[${account.name.replace(/\|/g, "\\|")}](${layout.accountDir}${slugs.get(account.id)}.md)`;
    lines.push(`| ${link} | ${account.stage} | ${account.priority} | ${account.owner} | ${account.health ?? "unknown"} | ${day(account.lastTouch)} | ${tick(account.id)} |`);
  }
  return lines.join("\n") + "\n";
}

export function accountRecords(workspace: Workspace, account: Account) {
  return {
    deals: workspace.deals.filter((deal) => deal.accountId === account.id),
    tasks: workspace.tasks.filter((task) => task.accountId === account.id),
    notes: workspace.notes.filter((note) => note.accountId === account.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt)),
  };
}

export function buildViewFiles(workspace: Workspace, layout: ViewLayout, notice = false): ViewFile[] {
  const slugs = uniqueSlugs(workspace.accounts);
  const files: ViewFile[] = [{ path: layout.indexPath, content: indexMarkdown(workspace, slugs, layout, notice) }];
  for (const account of workspace.accounts) {
    const { deals, tasks, notes } = accountRecords(workspace, account);
    files.push({ path: `${layout.accountDir}${slugs.get(account.id)}.md`, content: accountMarkdown(account, deals, tasks, notes, notice) });
  }
  return files;
}
